name: iOS Unit Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: macos-latest

    steps:

      - name: List available simulators
        run: xcrun simctl list devices
        
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Xcode
        uses: apple-actions/setup-xcode@v3
        with:
          xcode-version: '16.1'  # Убедитесь, что версия актуальна

      - name: List available simulators
        run: xcrun simctl list devices

      - name: Build and test
        run: |
          xcodebuild test \
            -project CalculatorApp.xcodeproj \
            -scheme CalculatorApp \
            -destination 'platform=iOS Simulator,name=iPhone 14,OS=18.2' \
            ONLY_ACTIVE_ARCH=YES
